package GUI;

import DatabaseLayer.DatabaseConnection;

import com.sun.glass.events.KeyEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class ManageIngredientsUI extends javax.swing.JFrame
{

    DatabaseConnection conn;

    public ManageIngredientsUI()
    {
        initComponents();

        conn = DatabaseConnection.getSingleConnection();

        //Call displayTable() method to populate jTableManageIngredients table.
        displayTable();
    }

    //Method to populate jTableManageIngredients table.
    void displayTable()
    {
        try
        {
            conn.get("SELECT * FROM Ingredients123456789");

            while (conn.rs.next())
            {
                String ID = conn.rs.getString(1);
                String Name = conn.rs.getString(2);
                String unitPrice = conn.rs.getString(3);

                Object[] content =
                {
                    ID, Name, unitPrice
                };

                DefaultTableModel model = (DefaultTableModel) jTableManageIngredients.getModel();

                model.addRow(content);
            }
        } catch (Exception e)
        {
        }

    }

    //Method to emptying out jTableManageIngredients table.
    void emptyTable()
    {
        DefaultTableModel model = (DefaultTableModel) jTableManageIngredients.getModel();

        int count = model.getRowCount();

        for (int i = 0; i < count; i++)
        {
            model.removeRow(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jDialogAddIngredient = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIIngredientID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldUnitPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonCloseAddEmployee = new javax.swing.JButton();
        jDialogChangeIngredient = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNewUnitPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonAddChange = new javax.swing.JButton();
        jButtonCloseChange = new javax.swing.JButton();
        jLabelIngredientID = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelPreviousUnitPrice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableManageIngredients = new javax.swing.JTable();
        jButtonDeleteIngredients = new javax.swing.JButton();
        jButtonAddIngredients = new javax.swing.JButton();
        jButtonChangeIngredients = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        jDialogAddIngredient.setTitle("Add Ingredient");
        jDialogAddIngredient.setLocationByPlatform(true);
        jDialogAddIngredient.setMinimumSize(new java.awt.Dimension(390, 420));
        jDialogAddIngredient.setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("IngredientID ");

        jTextFieldIIngredientID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldIIngredientID.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextFieldIIngredientIDKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Name");

        jTextFieldName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextFieldNameKeyTyped(evt);
            }
        });

        jTextFieldUnitPrice.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldUnitPrice.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextFieldUnitPriceKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("UnitPrice");

        jButtonAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCloseAddEmployee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonCloseAddEmployee.setText("Close");
        jButtonCloseAddEmployee.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCloseAddEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogAddIngredientLayout = new javax.swing.GroupLayout(jDialogAddIngredient.getContentPane());
        jDialogAddIngredient.getContentPane().setLayout(jDialogAddIngredientLayout);
        jDialogAddIngredientLayout.setHorizontalGroup(
            jDialogAddIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddIngredientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogAddIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddIngredientLayout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddIngredientLayout.createSequentialGroup()
                        .addGroup(jDialogAddIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(67, 67, 67)
                        .addGroup(jDialogAddIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIIngredientID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialogAddIngredientLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButtonCloseAddEmployee)))
                        .addGap(60, 60, 60))))
        );
        jDialogAddIngredientLayout.setVerticalGroup(
            jDialogAddIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddIngredientLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jDialogAddIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIIngredientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jDialogAddIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130)
                .addGroup(jDialogAddIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCloseAddEmployee)
                    .addComponent(jButtonAdd))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jDialogChangeIngredient.setTitle("Change Ingredient");
        jDialogChangeIngredient.setLocationByPlatform(true);
        jDialogChangeIngredient.setMinimumSize(new java.awt.Dimension(390, 420));
        jDialogChangeIngredient.setResizable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("IngredientID ");

        jTextFieldNewUnitPrice.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldNewUnitPrice.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextFieldNewUnitPriceKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("New UnitPrice");

        jButtonAddChange.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAddChange.setText("Add");
        jButtonAddChange.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAddChangeActionPerformed(evt);
            }
        });

        jButtonCloseChange.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonCloseChange.setText("Close");
        jButtonCloseChange.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCloseChangeActionPerformed(evt);
            }
        });

        jLabelIngredientID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabelName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Name");

        jLabelPreviousUnitPrice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Previous UnitPrice");

        javax.swing.GroupLayout jDialogChangeIngredientLayout = new javax.swing.GroupLayout(jDialogChangeIngredient.getContentPane());
        jDialogChangeIngredient.getContentPane().setLayout(jDialogChangeIngredientLayout);
        jDialogChangeIngredientLayout.setHorizontalGroup(
            jDialogChangeIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogChangeIngredientLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jDialogChangeIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(67, 67, 67)
                .addGroup(jDialogChangeIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNewUnitPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabelIngredientID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPreviousUnitPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
            .addGroup(jDialogChangeIngredientLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jDialogChangeIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogChangeIngredientLayout.createSequentialGroup()
                        .addComponent(jButtonAddChange)
                        .addGap(122, 122, 122))
                    .addComponent(jButtonCloseChange, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogChangeIngredientLayout.setVerticalGroup(
            jDialogChangeIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogChangeIngredientLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jDialogChangeIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelIngredientID, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jDialogChangeIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(34, 34, 34)
                .addGroup(jDialogChangeIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPreviousUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jDialogChangeIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNewUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jDialogChangeIngredientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCloseChange)
                    .addComponent(jButtonAddChange))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Ingredient");
        setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Ingredients", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jTableManageIngredients.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTableManageIngredients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "IngredientID", "Name", "UnitPrice "
            }
        ));
        jScrollPane1.setViewportView(jTableManageIngredients);

        jButtonDeleteIngredients.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonDeleteIngredients.setText("Delete Ingredient");
        jButtonDeleteIngredients.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDeleteIngredientsActionPerformed(evt);
            }
        });

        jButtonAddIngredients.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAddIngredients.setText("Add Ingredient");
        jButtonAddIngredients.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAddIngredientsActionPerformed(evt);
            }
        });

        jButtonChangeIngredients.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonChangeIngredients.setText("Change Ingredient");
        jButtonChangeIngredients.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonChangeIngredientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAddIngredients)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonChangeIngredients)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonDeleteIngredients))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeleteIngredients)
                    .addComponent(jButtonAddIngredients)
                    .addComponent(jButtonChangeIngredients))
                .addGap(32, 32, 32))
        );

        jButtonClose.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonClose)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClose)
                .addGap(57, 57, 57))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteIngredientsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDeleteIngredientsActionPerformed
    {//GEN-HEADEREND:event_jButtonDeleteIngredientsActionPerformed

        //Delete an item from Ingredients123456789 table.
        DefaultTableModel model = (DefaultTableModel) jTableManageIngredients.getModel();

        if (jTableManageIngredients.getSelectedRow() == -1)
        {
            if (jTableManageIngredients.getRowCount() == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "No Data to Delete.", "Manage Ingredients", JOptionPane.OK_OPTION);
            } else
            {
                JOptionPane.showMessageDialog(rootPane, "Select a Row to Delete.", "Manage Ingredients", JOptionPane.OK_OPTION);
            }
        } else
        {
            String ID = jTableManageIngredients.getValueAt(jTableManageIngredients.getSelectedRow(), 0).toString();

            ID = "DELETE FROM Ingredients123456789 WHERE IngredientID=" + ID;

            boolean status = conn.deleteRow(ID);

            if (status)
            {
                JOptionPane.showMessageDialog(rootPane, "Successfully Deleted.", "Manage Ingredients", JOptionPane.PLAIN_MESSAGE);
                model.removeRow(jTableManageIngredients.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jButtonDeleteIngredientsActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCloseActionPerformed
    {//GEN-HEADEREND:event_jButtonCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonAddIngredientsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddIngredientsActionPerformed
    {//GEN-HEADEREND:event_jButtonAddIngredientsActionPerformed
        jDialogAddIngredient.setVisible(true);

        jTextFieldIIngredientID.setText("");
        jTextFieldName.setText("");
        jTextFieldUnitPrice.setText("");
    }//GEN-LAST:event_jButtonAddIngredientsActionPerformed

    private void jButtonCloseAddEmployeeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCloseAddEmployeeActionPerformed
    {//GEN-HEADEREND:event_jButtonCloseAddEmployeeActionPerformed
        jDialogAddIngredient.setVisible(false);
    }//GEN-LAST:event_jButtonCloseAddEmployeeActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddActionPerformed
    {//GEN-HEADEREND:event_jButtonAddActionPerformed
        //Adding new Ingredients to the Ingredients123456789 table.

        int ID = Integer.parseInt(jTextFieldIIngredientID.getText());
        String name = jTextFieldName.getText();
        int unitPrice = Integer.parseInt(jTextFieldUnitPrice.getText());

        String query = "INSERT INTO Ingredients123456789 VALUES (" + ID + ",'" + name + "'," + unitPrice + ")";

        System.out.println(query);

        boolean status = conn.insert(query);

        jDialogAddIngredient.setVisible(false);

        //Refresh jTableManageIngredients table.
        emptyTable();

        displayTable();

        if (status)
        {
            JOptionPane.showMessageDialog(rootPane, "Successfully Added.", "Add Ingredient", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    //Input Validiation.

    private void jTextFieldUnitPriceKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldUnitPriceKeyTyped
    {//GEN-HEADEREND:event_jTextFieldUnitPriceKeyTyped
        char key = evt.getKeyChar();

        if (!(Character.isDigit(key)) || key == KeyEvent.VK_BACKSPACE || key == KeyEvent.VK_DELETE)
        {
            evt.consume();
        }

        if (jTextFieldUnitPrice.getText().length() >= 4)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldUnitPriceKeyTyped

    private void jTextFieldNameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldNameKeyTyped
    {//GEN-HEADEREND:event_jTextFieldNameKeyTyped
        char key = evt.getKeyChar();

        if (!(Character.isLetter(key)) || key == KeyEvent.VK_BACKSPACE || key == KeyEvent.VK_DELETE)
        {
            evt.consume();
        }

        if (jTextFieldName.getText().length() >= 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNameKeyTyped

    private void jTextFieldIIngredientIDKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldIIngredientIDKeyTyped
    {//GEN-HEADEREND:event_jTextFieldIIngredientIDKeyTyped
        char key = evt.getKeyChar();

        if (!(Character.isDigit(key)) || key == KeyEvent.VK_BACKSPACE || key == KeyEvent.VK_DELETE)
        {
            evt.consume();
        }

        if (jTextFieldIIngredientID.getText().length() >= 5)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldIIngredientIDKeyTyped

    private void jButtonChangeIngredientsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonChangeIngredientsActionPerformed
    {//GEN-HEADEREND:event_jButtonChangeIngredientsActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableManageIngredients.getModel();

        if (jTableManageIngredients.getSelectedRow() == -1)
        {
            if (jTableManageIngredients.getRowCount() == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "No Data to Change.", "Manage Ingredients", JOptionPane.OK_OPTION);
            } else
            {
                JOptionPane.showMessageDialog(rootPane, "Select a Row to Change.", "Manage Ingredients", JOptionPane.OK_OPTION);
            }
        } else
        {
            String ID = jTableManageIngredients.getValueAt(jTableManageIngredients.getSelectedRow(), 0).toString();

            jLabelIngredientID.setText(ID);

            try
            {

                String query = "SELECT * FROM Ingredients123456789 WHERE IngredientID = " + ID;

                conn.get(query);

                while (conn.rs.next())
                {
                    String name = conn.rs.getString("Name");

                    jLabelName.setText(name);

                    String previousUnitPrice = conn.rs.getString("UnitPrice");

                    jLabelPreviousUnitPrice.setText(previousUnitPrice);
                }
            } catch (Exception e)
            {

            }

            jDialogChangeIngredient.setVisible(true);
        }
    }//GEN-LAST:event_jButtonChangeIngredientsActionPerformed

    private void jTextFieldNewUnitPriceKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldNewUnitPriceKeyTyped
    {//GEN-HEADEREND:event_jTextFieldNewUnitPriceKeyTyped
        char key = evt.getKeyChar();

        if (!(Character.isDigit(key)) || key == KeyEvent.VK_BACKSPACE || key == KeyEvent.VK_DELETE)
        {
            evt.consume();
        }

        if (jTextFieldNewUnitPrice.getText().length() >= 4)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNewUnitPriceKeyTyped

    private void jButtonAddChangeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddChangeActionPerformed
    {//GEN-HEADEREND:event_jButtonAddChangeActionPerformed
        int ID = Integer.parseInt(jTableManageIngredients.getValueAt(jTableManageIngredients.getSelectedRow(), 0).toString());

        int newPrice = Integer.parseInt(jTextFieldNewUnitPrice.getText());

        String query = "UPDATE Ingredients123456789 SET UnitPrice = " + newPrice + " WHERE IngredientID = " + ID;

        System.out.println(ID);

        System.out.println(newPrice);
        
        System.out.println(query);

        boolean status = conn.insert(query);

        emptyTable();

        displayTable();
        
        jDialogChangeIngredient.setVisible(false);

        if (status)
        {
            JOptionPane.showMessageDialog(rootPane, "Successfully Changed.", "Manage Ingredients", JOptionPane.PLAIN_MESSAGE);
        }


    }//GEN-LAST:event_jButtonAddChangeActionPerformed

    private void jButtonCloseChangeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCloseChangeActionPerformed
    {//GEN-HEADEREND:event_jButtonCloseChangeActionPerformed
        jDialogChangeIngredient.setVisible(false);
    }//GEN-LAST:event_jButtonCloseChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ManageIngredientsUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ManageIngredientsUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ManageIngredientsUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ManageIngredientsUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ManageIngredientsUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddChange;
    private javax.swing.JButton jButtonAddIngredients;
    private javax.swing.JButton jButtonChangeIngredients;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonCloseAddEmployee;
    private javax.swing.JButton jButtonCloseChange;
    private javax.swing.JButton jButtonDeleteIngredients;
    private javax.swing.JDialog jDialogAddIngredient;
    private javax.swing.JDialog jDialogChangeIngredient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelIngredientID;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPreviousUnitPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableManageIngredients;
    private javax.swing.JTextField jTextFieldIIngredientID;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNewUnitPrice;
    private javax.swing.JTextField jTextFieldUnitPrice;
    // End of variables declaration//GEN-END:variables
}
