package GUI;

import DatabaseLayer.DatabaseConnection;

import com.sun.glass.events.KeyEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class ManageEmployeesGUI extends javax.swing.JFrame
{

    DatabaseConnection conn;

    public ManageEmployeesGUI()
    {
        initComponents();

        conn = DatabaseConnection.getSingleConnection();
        
        //Call displayTable() method to populate jTableManageEmployee table.

        displayTable();
    }
    
    //Method to populate jTableManageEmployee table.

    void displayTable()
    {
        try
        {
            conn.get("SELECT * FROM Emp123456789");

            while (conn.rs.next())
            {
                String ID = conn.rs.getString(1);
                String NIC = conn.rs.getString(2);
                String Name = conn.rs.getString(3);
                String Age = conn.rs.getString(4);

                Object[] content =
                {
                    ID, NIC, Name, Age
                };

                DefaultTableModel model = (DefaultTableModel) jTableManageEmployee.getModel();

                model.addRow(content);
            }
        } catch (Exception e)
        {
        }

    }
    
     //Method to emptying out jTableManageEmployee table.

    void refreshTable()
    {
        DefaultTableModel model = (DefaultTableModel) jTableManageEmployee.getModel();

        int count = model.getRowCount();

        for (int i = 0; i < count; i++)
        {
            model.removeRow(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDialogAddEmployee = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIID = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextFieldNIC = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonCloseAddEmployee = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableManageEmployee = new javax.swing.JTable();
        jButtonDeleteEmployee = new javax.swing.JButton();
        jButtonAddEmployee = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jDialogAddEmployee.setTitle("Add Employee");
        jDialogAddEmployee.setLocationByPlatform(true);
        jDialogAddEmployee.setMinimumSize(new java.awt.Dimension(390, 420));
        jDialogAddEmployee.setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("ID");

        jTextFieldIID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldIID.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextFieldIIDKeyTyped(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelName.setText("NIC");

        jTextFieldNIC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldNIC.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextFieldNICKeyTyped(evt);
            }
        });

        jTextFieldName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextFieldNameKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Name");

        jTextFieldAge.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldAge.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jTextFieldAgeKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Age");

        jButtonAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCloseAddEmployee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonCloseAddEmployee.setText("Close");
        jButtonCloseAddEmployee.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCloseAddEmployeeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("V");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Password");

        jPasswordFieldPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPasswordFieldPassword.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jPasswordFieldPasswordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jDialogAddEmployeeLayout = new javax.swing.GroupLayout(jDialogAddEmployee.getContentPane());
        jDialogAddEmployee.getContentPane().setLayout(jDialogAddEmployeeLayout);
        jDialogAddEmployeeLayout.setHorizontalGroup(
            jDialogAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddEmployeeLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jDialogAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddEmployeeLayout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddEmployeeLayout.createSequentialGroup()
                        .addGroup(jDialogAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabelName)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jDialogAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialogAddEmployeeLayout.createSequentialGroup()
                                .addComponent(jTextFieldNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialogAddEmployeeLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButtonCloseAddEmployee))
                            .addGroup(jDialogAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                        .addGap(45, 45, 45))))
        );
        jDialogAddEmployeeLayout.setVerticalGroup(
            jDialogAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddEmployeeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jDialogAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(jDialogAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jDialogAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(jDialogAddEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCloseAddEmployee)
                    .addComponent(jButtonAdd))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Employees");
        setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1100, 700));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jTableManageEmployee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTableManageEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "NIC", "Name", "Age"
            }
        ));
        jScrollPane1.setViewportView(jTableManageEmployee);

        jButtonDeleteEmployee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonDeleteEmployee.setText("Delete Employee");
        jButtonDeleteEmployee.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDeleteEmployeeActionPerformed(evt);
            }
        });

        jButtonAddEmployee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAddEmployee.setText("Add Employee");
        jButtonAddEmployee.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonAddEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAddEmployee)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteEmployee))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeleteEmployee)
                    .addComponent(jButtonAddEmployee))
                .addGap(32, 32, 32))
        );

        jButtonClose.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(877, 877, 877)
                        .addComponent(jButtonClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButtonClose)
                .addGap(57, 57, 57))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDeleteEmployeeActionPerformed
    {//GEN-HEADEREND:event_jButtonDeleteEmployeeActionPerformed

        //Delete an item from Ingredients123456789 table.
        
        DefaultTableModel model = (DefaultTableModel) jTableManageEmployee.getModel();

        if (jTableManageEmployee.getSelectedRow() == -1)
        {
            if (jTableManageEmployee.getRowCount() == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "No Data to Delete.", "Manage Employee", JOptionPane.OK_OPTION);
            } else
            {
                JOptionPane.showMessageDialog(rootPane, "Select a Row to Delete.", "Manage Employee", JOptionPane.OK_OPTION);
            }
        } else
        {
            String ID = jTableManageEmployee.getValueAt(jTableManageEmployee.getSelectedRow(), 0).toString();

            ID = "DELETE FROM Emp123456789 WHERE EmpID=" + ID;

            boolean status = conn.deleteRow(ID);

            if (status)
            {
                JOptionPane.showMessageDialog(rootPane, "Successfully Deleted.", "Edit Employee", JOptionPane.PLAIN_MESSAGE);
                model.removeRow(jTableManageEmployee.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jButtonDeleteEmployeeActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCloseActionPerformed
    {//GEN-HEADEREND:event_jButtonCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonAddEmployeeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddEmployeeActionPerformed
    {//GEN-HEADEREND:event_jButtonAddEmployeeActionPerformed
        jDialogAddEmployee.setVisible(true);

        jTextFieldIID.setText("");
        jTextFieldNIC.setText("");
        jTextFieldName.setText("");
        jTextFieldAge.setText("");
        jPasswordFieldPassword.setText("");
    }//GEN-LAST:event_jButtonAddEmployeeActionPerformed

    private void jButtonCloseAddEmployeeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCloseAddEmployeeActionPerformed
    {//GEN-HEADEREND:event_jButtonCloseAddEmployeeActionPerformed
        jDialogAddEmployee.setVisible(false);
    }//GEN-LAST:event_jButtonCloseAddEmployeeActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAddActionPerformed
    {//GEN-HEADEREND:event_jButtonAddActionPerformed
        ////Adding new Employee to the Emp123456789 table.
        
        int ID = Integer.parseInt(jTextFieldIID.getText());
        String NIC = jTextFieldNIC.getText();
        String name = jTextFieldName.getText();
        int age = Integer.parseInt(jTextFieldAge.getText());
        String password = jPasswordFieldPassword.getText();

        NIC = NIC + "v";

        String query = "INSERT INTO Emp123456789 VALUES (" + ID + ",'" + NIC + "','" + name + "'," + age + ",'" + password + "')";

        boolean status = conn.insert(query);

        jDialogAddEmployee.setVisible(false);

        refreshTable();

        displayTable();

        if (status)
        {
            JOptionPane.showMessageDialog(rootPane, "Successfully Added.", "Add Employee", JOptionPane.PLAIN_MESSAGE);
        }

    }//GEN-LAST:event_jButtonAddActionPerformed

    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    //Input Validiation.
    
    private void jTextFieldIIDKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldIIDKeyTyped
    {//GEN-HEADEREND:event_jTextFieldIIDKeyTyped
        char key = evt.getKeyChar();

        if (!(Character.isDigit(key)) || key == KeyEvent.VK_BACKSPACE || key == KeyEvent.VK_DELETE)
        {
            evt.consume();
        }

        if (jTextFieldIID.getText().length() >= 3)
        {
            evt.consume();
        }

    }//GEN-LAST:event_jTextFieldIIDKeyTyped

    private void jTextFieldNICKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldNICKeyTyped
    {//GEN-HEADEREND:event_jTextFieldNICKeyTyped
        char key = evt.getKeyChar();

        if (!(Character.isDigit(key)) || key == KeyEvent.VK_BACKSPACE || key == KeyEvent.VK_DELETE)
        {
            evt.consume();
        }

        if (jTextFieldNIC.getText().length() >= 9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNICKeyTyped

    private void jTextFieldNameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldNameKeyTyped
    {//GEN-HEADEREND:event_jTextFieldNameKeyTyped
        char key = evt.getKeyChar();

        if (!(Character.isLetter(key)) || key == KeyEvent.VK_BACKSPACE || key == KeyEvent.VK_DELETE)
        {
            evt.consume();
        }

        if (jTextFieldName.getText().length() >= 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNameKeyTyped

    private void jTextFieldAgeKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTextFieldAgeKeyTyped
    {//GEN-HEADEREND:event_jTextFieldAgeKeyTyped
        char key = evt.getKeyChar();

        if (!(Character.isDigit(key)) || key == KeyEvent.VK_BACKSPACE || key == KeyEvent.VK_DELETE)
        {
            evt.consume();
        }

        if (jTextFieldAge.getText().length() >= 2)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldAgeKeyTyped

    private void jPasswordFieldPasswordKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jPasswordFieldPasswordKeyTyped
    {//GEN-HEADEREND:event_jPasswordFieldPasswordKeyTyped
        char key = evt.getKeyChar();

        if (!(Character.isLetterOrDigit(key)) || key == KeyEvent.VK_BACKSPACE || key == KeyEvent.VK_DELETE)
        {
            evt.consume();
        }

        if (jTextFieldName.getText().length() >= 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jPasswordFieldPasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ManageEmployeesGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ManageEmployeesGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ManageEmployeesGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ManageEmployeesGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ManageEmployeesGUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddEmployee;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonCloseAddEmployee;
    private javax.swing.JButton jButtonDeleteEmployee;
    private javax.swing.JDialog jDialogAddEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableManageEmployee;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldIID;
    private javax.swing.JTextField jTextFieldNIC;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
